export const PREGUNTAS = [
    {
      "id": 1,
      "pregunta": "¿Cuál era la moneda utilizada en España antes del euro?",
      "respuesta": "La Peseta",
      "opciones": ["El eurillo","El Dolar", "La Peseta", "Siempre ha utilizado el Euro"],
      "categoria": "Historia",
      "nivel": "Facil",
      "imagen": "1.jpg",
    },
    {
      "id": 2,
      "pregunta": "¿Qué dos exploradores fueron los encargados de dar la primera vuelta al mundo?",
      "respuesta": "Magallanes y Elcano",
      "opciones": ["Magallanes y Elcano", "Julio Verne y su Esposa", "Hermanos Wild", "Elisa y su Esposo"],
      "categoria": "Historia",
      "nivel": "Dificil",
      "imagen": "2.jpg",
    },
    {
      "id": 3,
      "pregunta": "¿En qué isla encarcelaron a Napoleón tras perder la batalla de Waterloo?",
      "respuesta": "Santa Elena",
      "opciones": ["Santa Fe", "Santa Elena", "Isla de la Juventud", "Isla de San Cristóbal"],
      "categoria": "Historia",
      "nivel": "Normal",
      "imagen": "3.jpg",
    },
    {
      "id": 4,
      "pregunta": "¿Quién se considera el gran precursor del existencialismo?",
      "respuesta": "El filósofo danés Søren Kierkegaard",
      "opciones": ["EL filosofo socrates", "El filósofo danés Søren Kierkegaard", "El filósofo francés Claude Monet", "El filósofo francés Claude Monet"],
      "categoria": "Historia",
      "nivel": "Dios",
      "imagen": "4.jpg",
    },
    {
      "id": 5,
      "pregunta": "¿A qué rey considera de gran importancia el movimiento rastafari?",
      "respuesta": "Al rey Haile Selassie I",
      "opciones": ["El rey Carlomagno", "Al rey Haile Selassie I", "Al rey Haile Selassie II", "Al rey Haile Selassie III"],
      "categoria": "Historia",
      "nivel": "Titán",
      "imagen": "5.jpg",
    },
    {
      "id": 6,
      "pregunta": "¿Cómo se denominan a las bases del ADN?",
      "respuesta": "Guanina, adenina, timina y citosina",
      "opciones": ["Guanina, adenina, timina y citosina", "Guanabana, adeno, timida y xitocina", "Guainia, adeciva, tiamina, citrocina", "Acido, Ribuno, cleico, Adenoso"],
      "categoria": "Naturaleza y ciencias",
	  "nivel": "Facil",
      "imagen": "6.jpg",
    },
    {
      "id": 7,
      "pregunta": "A.m. es una abreviación que se sitúa detrás de una hora. ¿Qué significado tiene?",
      "respuesta": "Significa 'antes del meridiano'",
      "opciones": ["Significa 'antes del medio dia'", "Significa 'antes de la mañana'", "Significa 'antes del meridiano'", "Significa 'ante maritiva'"],
      "categoria": "Naturaleza y ciencias",
	  "nivel": "Normal",
      "imagen": "7.jpg",
    },
    {
      "id": 8,
      "pregunta": "¿Qué célula se encuentra tanto en humanos como en animales?",
      "respuesta": "La neurona",
      "opciones": ["La neurona", "La bacteria", "La parasita", "La célula del virosa"],
      "categoria": "Naturaleza y ciencias",
	  "nivel": "Dificil",
      "imagen": "8.jpg",
    },
    {
      "id": 9,
      "pregunta": "E=mc2 es una fórmula incluida en una teoría científica. ¿Cuál?",
      "respuesta": "En la teoría de la relatividad de Albert Einstein. ",
      "opciones": ["En la teoría de la relatividad de Newton.", "En la teoría de la relatividad de Albert Einstein.",  "En la teoría de la relatividad de Socrates", "En la teoría de la relatividad de Jimmy Neutrón."],
      "categoria": "Naturaleza y ciencias",
	  "nivel": "Dios",
      "imagen": "9.jpg",
    },
    {
      "id": 10,
      "pregunta": "¿Cómo se arregla una caries?",
      "respuesta": "Mediante un empaste",
      "opciones": ["Mediante un empaste", "Sacando el diente", "Con crema de dientes", "Pidiendole a DIos"],
      "categoria": "Naturaleza y ciencias",
	  "nivel": "Titán",
      "imagen": "10.png",
    },
	{
		"id": 11,
		"pregunta": "¿Cómo se llamaba el cantante de Queen?",
		"respuesta": "Freddy Mercury",
		"opciones": ["Freddy Crugger", "Freddy Mercury", "Freddy Vega", "Freddy Venus"],
		"categoria": "Entretenimiento",
		"nivel": "Facil",
		"imagen": "11.jpg"
	},
	{
		"id": 12,
		"pregunta": "¿A qué grupo musical pertenece la canción 'Smells like teen spirit'?",
		"respuesta": "Nirvana",
		"opciones": ["Nirvana", "Metallica", "Gun's and roses", "Beatles"],
		"categoria": "Entretenimiento",
		"nivel": "Normal",
		"imagen": "12.jpg"
	},
	{
		"id": 13,
		"pregunta": "¿Quién es el antagonista de la película 'El Rey León'?",
		"respuesta": "Scar",
		"opciones": ["Timon", "Pumba", "Tinkerbell", "Scar"],
		"categoria": "Entretenimiento",
		"nivel": "Dificil",
		"imagen": "13.jpg"
	},
	{
		"id": 14,
		"pregunta": "¿Qué película hizo famoso al director James Cameron?",
		"respuesta": "Titanic",
		"opciones": ["Titanic", "Avatar", "Terminator", "Rambo"],
		"categoria": "Entretenimiento",
		"nivel": "Dios",
		"imagen": "14.jpg"
	},
	{
		"id": 15,
		"pregunta": "¿En qué festival hay desfiles cuyos directores son escuelas de samba?",
		"respuesta": "El Carnaval de Brasil",
		"opciones": ["El Carnaval de las flores", "El Festival de la samba", "El Festival du Soleil", "El Carnaval de Brasil"],
		"categoria": "Entretenimiento",
		"nivel": "Titán",
		"imagen": "15.jpg"
	},
	{
		"id": 16,
		"pregunta": "¿Quién es el pintor que creo la Mona Lisa?",
		"respuesta": "",
		"opciones": ["Leonardo Di Caprio", "Ruben Aguirre", "Leopoldo Bonaparte", "Leonardo da Vinci"],
		"categoria": "Arte y literatura",
		"nivel": "Facil",
		"imagen": "16.jpg"
	},
	{
		"id": 17,
		"pregunta": "¿Quién es el autor de la Ilíada y la Odisea?",
		"respuesta": "Homero",
		"opciones": ["Homero", "Odiseo", "Mou", "Zeus"],
		"categoria": "Arte y literatura",
		"nivel": "Normal",
		"imagen": "17.jpg"
	},
	{
		"id": 18,
		"pregunta": "Notre Dame es una catedral con un estilo arquitectónico muy definido. ¿Cuál?",
		"respuesta": "Estilo gótico",
		"opciones": ["Estilo moderno", "Estilo contemporaneo", "Estilo gótico", "Estilo darks"],
		"categoria": "Arte y literatura",
		"nivel": "Dificil",
		"imagen": "18.jpg"
	},
	{
		"id": 19,
		"pregunta": "'Ser o no ser, esa es la cuestión' es un soliloquio que pertenece a una obra de Shakespeare. ¿Cómo se llama?",
		"respuesta": "Hamlet",
		"opciones": ["Existencial", "Hamlet", "Descubriendo mi yo", "Ontologia mediatica"],
		"categoria": "Arte y literatura",
		"nivel": "Dios",
		"imagen": "19.jpg"
	},
	{
		"id": 20,
		"pregunta": "¿Cómo se titula el clásico de ciencia ficción dirigido por Fritz Lang?",
		"respuesta": "Metrópolis",
		"opciones": ["Metrópolis", "EL futuro es aqui", "La era de los simios", "La era de Ultron"],
		"categoria": "Arte y literatura",
		"nivel": "Titán",
		"imagen": "20.jpg"
	},
	{
		"id": 21,
		"pregunta": "¿Qué colores componen los anillos olímpicos?",
		"respuesta": "Negro, rojo, azul, amarillo y verde",
		"opciones": ["Negro, rosado, azul, amarillo y verde", "Negro, rojo, blanco, amarillo y verde", "Negro, rojo, azul, violeta y verde", "Negro, rojo, azul, amarillo y verde"],
		"categoria": "Deportes",
		"nivel": "Facil",
		"imagen": "21.png"
	},
	{
		"id": 22,
		"pregunta": "Un atleta posee los récords mundiales de velocidad de 100 y 200 metros lisos. ¿Quién es?",
		"respuesta": "Usain Bolt",
		"opciones": ["Forest Gump", "Usain Bolt", "Leonardo Messi", "Cristiano Ronaldo"],
		"categoria": "Deportes",
		"nivel": "Normal",
		"imagen": "22.jpg"
	},
	{
		"id": 23,
		"pregunta": "¿Qué baile tiene su origen en un arte marcial?",
		"respuesta": "La capoeira",
		"opciones": ["La capoeira", "La zamba", "La salsa", "El judo"],
		"categoria": "Deportes",
		"nivel": "Dificil",
		"imagen": "23.jpg"
	},
	{
		"id": 24,
		"pregunta": "¿Cuál es el deporte más popular en la India?",
		"respuesta": "El críquet",
		"opciones": ["EL baseball", "El basketball", "El críquet", "El voleiball"],
		"categoria": "Deportes",
		"nivel": "Dios",
		"imagen": "24.jpg"
	},
	{
		"id": 25,
		"pregunta": "¿En qué equipo de la NBA estuvo Manu Ginobili entre 2002 y 2018?",
		"respuesta": "San Antonio Spurs",
		"opciones": ["San Antonio Spurs", "Miami", "Luxengburb", "The bulls"],
		"categoria": "Deportes",
		"nivel": "Titán",
		"imagen": "25.jpg"
	},
]
