export const PREGUNTAS = [
    {
      "id": 1,
      "pregunta": "¿Cuál era la moneda utilizada en España antes del euro?",
      "respuesta": "La Peseta",
      "opciones": ["El eurillo","El Dolar", "La Peseta", "Siempre ha utilizado el Euro"],
      "categoria": "Historia",
      "nivel": "Facil",
      "imagen": "1.jpg",
    },
    {
      "id": 2,
      "pregunta": "¿Qué dos exploradores fueron los encargados de dar la primera vuelta al mundo?",
      "respuesta": "Magallanes y Elcano",
      "opciones": ["Magallanes y Elcano", "Julio Verne y su Esposa", "Hermanos Wild", "Elisa y su Esposo"],
      "categoria": "Historia",
      "nivel": "Dificil",
      "imagen": "2.jpg",
    },
    {
      "id": 3,
      "pregunta": "¿En qué isla encarcelaron a Napoleón tras perder la batalla de Waterloo?",
      "respuesta": "Santa Elena",
      "opciones": ["Santa Fe", "Santa Elena", "Isla de la Juventud", "Isla de San Cristóbal"],
      "categoria": "Historia",
      "nivel": "Normal",
      "imagen": "3.jpg",
    },
    {
      "id": 4,
      "pregunta": "¿Quién se considera el gran precursor del existencialismo?",
      "respuesta": "El filósofo danés Søren Kierkegaard",
      "opciones": ["EL filosofo socrates", "El filósofo danés Søren Kierkegaard", "El filósofo francés Claude Monet", "El filósofo francés Claude Monet"],
      "categoria": "Historia",
      "nivel": "Dios",
      "imagen": "4.jpg",
    },
    {
      "id": 5,
      "pregunta": "¿A qué rey considera de gran importancia el movimiento rastafari?",
      "respuesta": "Al rey Haile Selassie I",
      "opciones": ["El rey Carlomagno", "Al rey Haile Selassie I", "Al rey Haile Selassie II", "Al rey Haile Selassie III"],
      "categoria": "Historia",
      "Nivel": "Titán",
      "imagen": "5.jpg",
    },
    {
      "id": 6,
      "pregunta": "¿Cómo se denominan a las bases del ADN?",
      "respuesta": "Guanina, adenina, timina y citosina",
      "opciones": ["Guanina, adenina, timina y citosina", "Guanabana, adeno, timida y xitocina", "Guainia, adeciva, tiamina, citrocina", "Acido, Ribuno, cleico, Adenoso"],
      "categoria": "Naturaleza y ciencias",
      "imagen": "6.jpg",
    },
    {
      "id": 7,
      "pregunta": "A.m. es una abreviación que se sitúa detrás de una hora. ¿Qué significado tiene?",
      "respuesta": "Significa 'antes del meridiano'",
      "opciones": ["Significa 'antes del medio dia'", "Significa 'antes de la mañana'", "Significa 'antes del meridiano'", "Significa 'ante maritiva'"],
      "categoria": "Naturaleza y ciencias",
      "imagen": "7.jpg",
    },
    {
      "id": 8,
      "pregunta": "¿Qué célula se encuentra tanto en humanos como en animales?",
      "respuesta": "La neurona",
      "opciones": ["La neurona", "La bacteria", "La parasita", "La célula del virosa"],
      "categoria": "Naturaleza y ciencias",
      "imagen": "8.jpg",
    },
    {
      "id": 9,
      "pregunta": "E=mc2 es una fórmula incluida en una teoría científica. ¿Cuál?",
      "respuesta": "En la teoría de la relatividad de Albert Einstein. ",
      "opciones": ["En la teoría de la relatividad de Newton.", "En la teoría de la relatividad de Albert Einstein.",  "En la teoría de la relatividad de Socrates", "En la teoría de la relatividad de Jimmy Neutrón."],
      "categoria": "Naturaleza y ciencias",
      "imagen": "9.jpg",
    },
    {
      "id": 10,
      "pregunta": "¿Cómo se arregla una caries?",
      "respuesta": "Mediante un empaste",
      "opciones": ["Mediante un empaste", "Sacando el diente", "Con crema de dientes", "Pidiendole a DIos"],
      "categoria": "Naturaleza y ciencias",
      "imagen": "10.jpg",
    },
]
